# TODO: find a better metric
DUPLICATE_DELTA = 2
MIN_LOG_LENGTH = 2
QUERY_LIMIT = 20

SPECIAL_PLAYERS = ["conjured sword", "saul d'alessio"]

REQUIRED_ENV_VARIABLES = ["DB_HOST", "DB_USERNAME", "DB_PASSWORD", "DB_NAME", "DISCORD_TOKEN"]